// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"clean/pkg/api"
	"clean/pkg/api/handler"
	"clean/pkg/config"
	"clean/pkg/db"
	"clean/pkg/repository"
	"clean/pkg/usecase"
)

// Injectors from wire.go:

func InitializeEvent(cfg config.Config) (*http.ServerHTTP, error) {
	sqlDB := db.ConnectDB(cfg)
	userRepository := repository.NewUserRepository(sqlDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	authRepository := repository.NewAuthRepository(sqlDB)
	authUseCase := usecase.NewAuthUseCase(authRepository)
	jwtService := usecase.NewJWTService()
	authHandler := handler.NewAuthHandler(authUseCase, jwtService)
	serverHTTP := http.NewServerHTTP(userHandler, authHandler)
	return serverHTTP, nil
}
